apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  namespace: monitoring
  labels:
    app: mongodb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      containers:
      - name: mongodb-exporter
        image: percona/mongodb_exporter:0.40
        imagePullPolicy: IfNotPresent
        args:
          - --mongodb.uri=mongodb://mongodb-service.mern-app.svc.cluster.local:27017/admin
          - --collect-all
          - --compatible-mode
        ports:
        - containerPort: 9216
          name: metrics